### ISSUE TITLE
misleading config.js vs checkup.json

### ISSUE THREAD

**Issue by DanielRuf** [sourcegraph/checkup#115]
Do we need both files?
Does config.js contain the checkup.json content?

Some parts like https://github.com/sourcegraph/checkup#file-system-storage mention it but https://github.com/sourcegraph/checkup#github-storage does not.

**Comment by parkr** [comment]
@DanielRuf Hey! They're actually very different:

- **checkup.json** – list of checks to run and configuration for storing/notifying when you run the `checkup` binary
- **config.js** – javascript loaded onto the website for viewing your check history. this is required for sites where you need secrets to read the stored checkup data.

Could the `checkup` binary write out this web configuration file based on the checkup.json? Maybe, but there's always the possibility that the user doesn't want to write and read from the same location (maybe they have a proxy for their S3 data so an access key and secret aren't put out into the world, for example). So it does make sense to separate them and have config.js manually crafted.

The reason the GitHub storage doesn't mention config.js, is because it describes using a public GitHub Pages site to host your check history, so there's no authentication required. It could mention adding one in order to configure status text and refresh intervals and the like, but it's not strictly necessary since the check history files are all hosted publicly on GitHub Pages.

**Comment by titpetric** [comment]
I'm thinking of defaulting to `fs` for the front-end checks - or at least have the config.js reflect that by default. As it stands, the status page is unconfigured at the beginning and when doing local testing (let alone s3/github), which means there aren't reasonable defaults set.

In the current pipeline there is postgres, mysql support (already opened PR), and reading from the sql store hasn't been supported until now either. Checkup will embed a HTTP server with `checkup serve` that will automatically serve the statuspage and files from these external sources as well (or just the local storage/fs source also).

**Comment by titpetric** [comment]
Ok, I figured out that the default config.json is better suited now - we have about 5 storage providers, and it doesn't make any sense to default to S3. The config for GitHub does need to be modified (the `url` value, at least), and I've tried to reflect that both in the new config.js and README.md. It's going to be merged in with #130 - and as far as serving it locally, I also implemented a `checkup serve` command which supports all storage providers except GH and S3 (those don't implement a local index/fetch interface for reading check results).

**Comment by DanielRuf** [comment]
This sounds good, thanks for taking the time to take a look into this, provide some answers and a clarification.

**Comment by jeremych1000** [comment]
> I also implemented a checkup serve command which supports all storage providers except GH and S3 (those don't implement a local index/fetch interface for reading check results).

I've just run into this problem - this contradicts with the readme which says checkup can serve results from S3. Which is the case? I was under the impression I can have one instance of checkup running `checkup --store` into S3, and another instance running `checkup serve` pulling from S3.

**Comment by titpetric** [comment]
@jeremych1000 the reading from S3 is implemented on the front-end, not on the back-end. The back-end only implements the writer for S3. Checkup serve with the s3 config.js should work fine - but if that's not the case, please fire up the browser JS/network console and open up a new issue.

**Comment by jeremych1000** [comment]
> @jeremych1000 the reading from S3 is implemented on the front-end, not on the back-end. The back-end only implements the writer for S3. Checkup serve with the s3 config.js should work fine - but if that's not the case, please fire up the browser JS/network console and open up a new issue.

Thanks for clearing that up, it does work (I get access denied in the console but that's due to my configuration of the bucket etc.) - it was slightly confusing how I couldn't have s3 configured in both `checkup.json` as well as `config.js`, as if I ran `checkup serve` with checkup.json configured to S3, it would overwrite config.js and output 'onfigured storage type does not have reading capabilities`.

@titpetric and @parkr another quick question - what's the recommended way to serve from S3 without baking in AWS keys?
You mention:
> maybe they have a proxy for their S3 data so an access key and secret aren't put out into the world, for example

How would this work? I tried with an s3 proxy i.e. only configure a `url` in `config.js` but it requests index.json - which doesn't exist in an S3 bucket.
