### ISSUE TITLE
Assertions in checks

### ISSUE THREAD

**Issue by victorb** [sourcegraph/checkup#5]
Would be nice to be able to set something like JSON assertions in the checks. Something like this:

``` json
{
    "checkers": [{
        "type": "http",
        "endpoint_name": "Example",
        "endpoint_url": "http://www.example.com",
        "attempts": 5,
        "assertions": {
             "response.body.status": "Ok!",
             "response.statusCode": 200,
         }
    }],
    "storage": {
        "provider": "s3",
        "access_key_id": "<yours>",
        "secret_access_key": "<yours>",
        "bucket": "<yours>"
    }
}
```

Basically what Runscope is offering. Example:

<img width="876" alt="screen shot 2016-08-07 at 16 16 42" src="https://cloud.githubusercontent.com/assets/459764/17462876/658e4450-5cba-11e6-8936-c5066615570e.png">

**Comment by mholt** [comment]
You can do this already to some extent [using these fields in an HTTP checker](https://github.com/sourcegraph/checkup/blob/09455c4a45b9776f8b2cd9cc51b907f79018b429/httpchecker.go#L20-L47). It is a pretty simple implementation of assertions.

**Comment by VictorBjelkholm** [comment]
That seems to be enough if you just want to do some simple checks, yeah.

My thought is around being able to specify JSON paths since I have some services that return status of connected services in the status endpoint. For example, an API might have the following response:

```json
{
  "mysql": true,
  "redis": false,
  "s3": true
}
```

And where it would be kind of messy to do string matching on the entire response instead of saying `response.data.mysql=true` or something like that.

**Comment by mholt** [comment]
Well, I'm sure we can look into this -- I'm not opposed as far as a feature request goes. I wonder how trivial it would be to implement.

**Comment by titpetric** [comment]
This is possible today by implementing a custom `exec` checker, e.g. by using `curl` and `jq` to fetch and inspect json data. Due to API change concerns, it's not likely that this may be implemented in checkup directly but only as an external check. I'd like to keep the API signature for checkup as light as possible to cover a generic majority of use cases.

Since we're also always assuming that you have full control over the endpoint in question, you could also provide custom "flattened" json output and check the contents with "must_contain". That won't work very well if you want to check multiple values from a single check.

If the opened issue is still relevant, please open a new issue. I'm closing this one due to age.
