### ISSUE TITLE
Is it dead?

### ISSUE THREAD

**Issue by jsieler** [sourcegraph/checkup#50]
Is this project currently dead?!

**Comment by zweizeichen** [comment]
Looks like it, which really is a shame. At first glance it looked just like what I needed. I then tried to use this today and quickly grew frustrated after an hour or so due to the undocumented `fs`stuff and other random, undocumented behaviour (#51).
However, this project has a lot of potential (1.7k+ stars etc.). There simply is no similar extensible, lightweight self-hosted solution. It would just need someone with write access to the repo to spend a couple of hours merging the outstanding pull requests and fixing the most severe bugs. Also, IMHO optionally embedding a small web-server and generating a lightweight, ready-to-use Docker container (just mount your config and maybe persistence directory if you're using `fs`) would go a long way towards usability and ease of deployment.

**Comment by DerfOh** [comment]
Anyone know if there is an active fork somewhere out there?

This would be way easier to use then setting up/configuring nagios.

**Comment by mholt** [comment]
I'll be spending a little bit of time on this repo this week, in the hopes of updating the docs, fixing a few of the frustrating bugs, and getting a new release out. No promises on many new features though, with the time I have.

**Comment by mholt** [comment]
Here ya go. :) https://github.com/sourcegraph/checkup/releases/tag/v0.2.0
