### ISSUE TITLE
How to store files locally instead of s3

### ISSUE THREAD

**Issue by westonganger** [sourcegraph/checkup#6]
How can you store files locally instead of on s3? If you can this should also be explained in the Readme.

**Comment by mholt** [comment]
This is indeed possible, you just need to write a storage adapter for some sort of local storage.

On the health-check side, it's simply a matter of implementing [the Storage interface](https://github.com/sourcegraph/checkup/blob/09455c4a45b9776f8b2cd9cc51b907f79018b429/checkup.go#L310-L313) and, I recommend the [Maintainer interface](https://github.com/sourcegraph/checkup/blob/09455c4a45b9776f8b2cd9cc51b907f79018b429/checkup.go#L315-L320) as well.

Then for the status page, you can just write a function that implements a few methods [like the S3 adapter does](https://github.com/sourcegraph/checkup/blob/master/statuspage/js/s3.js). It implements the three methods `setup`, `getChecksWithin`, and `getNewChecks`. Then, to use it, instead of [sourcing the s3.js file](https://github.com/sourcegraph/checkup/blob/09455c4a45b9776f8b2cd9cc51b907f79018b429/statuspage/index.html#L8), you source your custom storage adapter instead.

If your adapter is general enough for more people, we'd be happy to include it in this repository.

I should probably fill out a wiki page with this info. Will do that after the weekend.

**Comment by ubergesundheit** [comment]
Maybe you could implement a configurable aws endpoint, so that one could use s3 compatible storage solutions?

**Comment by rileytg** [comment]
i've got a pull in the works for this. so far just lets you specify a filename and it overwrites if it exists. I find this helpful in dev and for something like using [filebeat](https://github.com/elastic/beats) to ship to elasticsearch. 

@mholt are you open to just a Storage impl or would you like me to do Maintainer also?

**Comment by rileytg** [comment]
i was also considering appending instead of overwriting, that way its like a log file. In that case Maintainer is prolly needed right>
